// SPDX-License-Identifier: AGPL-3.0-only

//! `cs __markdown-help` — generate the mdBook Reference from the clap tree.
//!
//! This is the **markdown twin** of the `__man-page` machinery: where
//! `clap_mangen` renders `man/cs.1` from the live clap tree, this module
//! renders `docs/book/src/reference/*.md` — one page per
//! [`command_group_layout()`](crate::cmd::help) group — from the same
//! tree, via [`clap_markdown::help_markdown_command_custom`].
//!
//! Three properties make it the anti-drift spine of the Reference
//! (ADR-B1′ §5):
//!
//! - **The allowlist is `command_group_layout()`** (§5.2). Only the
//!   user-facing verbs listed there are published; every internal verb
//!   carries `#[command(hide = true)]` and is omitted from *both* the
//!   terminal help and this markdown — clap-markdown early-returns on
//!   `is_hide_set()`, so hiding a verb removes it here for free.
//! - **Grouping comes from the map, not from clap** (§5.3). clap 4.6 has
//!   no subcommand-grouping feature, and clap-markdown emits a flat dump;
//!   so we drive the per-group split ourselves, calling the public
//!   per-command renderer once per allowlisted slot.
//! - **CI diffs the generated bytes against the committed pages** (§5.5,
//!   `tests/help_goldens.rs`). Adding or changing a command's signature
//!   without regenerating fails the build. The reference is a *projection
//!   of the CLI that CI enforces*.

use std::fmt::Write as _;
use std::path::PathBuf;

use crate::cmd::help::{command_group_layout, CommandSlot};

/// Arguments for the hidden `__markdown-help` subcommand.
#[derive(clap::Args)]
pub struct Args {
    /// Directory to write the generated reference pages into (created if
    /// missing). Without `--out`, the manifest of filenames that *would*
    /// be written is printed to stdout — a cheap dry-run.
    #[arg(long, value_name = "DIR")]
    pub out: Option<PathBuf>,
}

/// One generated Reference page: its basename and full markdown body.
pub struct ReferencePage {
    /// Filename relative to `docs/book/src/reference/`, e.g. `lifecycle.md`.
    pub filename: String,
    /// The complete markdown content, banner and generated-notice included.
    pub content: String,
}

/// The per-page vocabulary banner (ADR-B1′ §5.6 / R1).
///
/// The command *names* are the physics metaphor, and the generated
/// `about=` strings reproduce physics-loaded language dozens of times
/// before a reader reaches the (last-section) Explanation chapter. Every
/// generated Reference page therefore carries this one-line pointer to
/// the canonical glossary — the terms are reachable from every page even
/// though the metaphor's *rationale* is taught only once, in Explanation.
const VOCAB_BANNER: &str =
    "> These commands use physics-inspired names (nucleate, evolve, decay, spore, …). \
New to the vocabulary? See [The physics vocabulary](../explanation/physics-vocabulary.md).";

/// HTML comment stamped at the top of every generated page so a human who
/// opens the file knows not to hand-edit it — the golden check would
/// revert them.
const GENERATED_NOTICE: &str =
    "<!-- GENERATED by `cs __markdown-help` from the clap tree — do not edit by hand. -->";

/// Run the `__markdown-help` subcommand.
///
/// With `--out DIR`, writes every page into `DIR`. Without it, prints the
/// manifest of filenames (dry-run). `root` is the fully-assembled clap
/// tree (`build_cli()`), passed in so the renderer and the golden test
/// walk byte-identical structures.
pub fn run(root: &clap::Command, args: &Args) -> anyhow::Result<()> {
    let pages = reference_pages(root);
    match &args.out {
        Some(dir) => {
            std::fs::create_dir_all(dir)
                .map_err(|e| anyhow::anyhow!("create reference dir {}: {e}", dir.display()))?;
            for page in &pages {
                let path = dir.join(&page.filename);
                std::fs::write(&path, page.content.as_bytes())
                    .map_err(|e| anyhow::anyhow!("write {}: {e}", path.display()))?;
            }
            eprintln!("wrote {} reference pages to {}", pages.len(), dir.display());
        }
        None => {
            for page in &pages {
                println!("{}", page.filename);
            }
        }
    }
    Ok(())
}

/// Build every generated Reference page from the clap `root`.
///
/// The set is `overview.md` (the root: about + global flags + group
/// index) followed by one page per `command_group_layout()` group. The
/// hand-written pages (`exit-codes.md`, `formulas.md`) are NOT produced
/// here — they are committed by hand and covered by the command-name grep
/// + linkcheck, not the golden diff (ADR-B1′ §5.7 / R7).
#[must_use]
pub fn reference_pages(root: &clap::Command) -> Vec<ReferencePage> {
    let mut pages = vec![overview_page(root)];
    for group in command_group_layout() {
        pages.push(group_page(root, group.title, group.slug, &group.slots));
    }
    pages
}

/// Render a single command (and its non-hidden subcommands) as a markdown
/// fragment, then normalise it so headings and usage lines carry the `cs`
/// prefix the per-command renderer omits (it only sees the subcommand).
fn render_command_fragment(sub: &clap::Command) -> String {
    let opts = clap_markdown::MarkdownOptions::new()
        .show_table_of_contents(false)
        .show_footer(false)
        .show_aliases(true);
    let raw = clap_markdown::help_markdown_command_custom(sub, &opts);
    // `write_help_markdown` always emits a per-command document title
    // (`# Command-Line Help for \`spark\``) and a boilerplate "This
    // document contains…" line — noise when the command is one section of
    // a group page. Drop both; the command's own `## ` heading follows.
    let trimmed: String = raw
        .lines()
        .filter(|l| {
            !l.starts_with("# Command-Line Help for ")
                && !l.starts_with("This document contains the help content for the ")
        })
        .collect::<Vec<_>>()
        .join("\n");
    // The per-command renderer starts its path at the subcommand, so a
    // heading reads `## \`nucleate\`` and usage reads `**Usage:** \`nucleate …\``.
    // Prefix both with `cs ` so the Reference matches how a reader types it.
    trimmed
        .trim_start_matches('\n')
        .replace("## `", "## `cs ")
        .replace("**Usage:** `", "**Usage:** `cs ")
}

/// The generated `overview.md`: the root `about`, the global flags, the
/// `--json` agent-first note, and an index linking each group page.
fn overview_page(root: &clap::Command) -> ReferencePage {
    let mut s = String::new();
    s.push_str(GENERATED_NOTICE);
    s.push_str("\n\n# CLI overview\n\n");
    s.push_str(VOCAB_BANNER);
    s.push_str("\n\n");
    if let Some(about) = root.get_about() {
        s.push_str(&about.to_string());
        s.push_str("\n\n");
    }
    s.push_str("## Global options\n\n");
    s.push_str("These flags are accepted before any subcommand and apply to every command:\n\n");
    s.push_str("| Flag | Effect |\n");
    s.push_str("|------|--------|\n");
    s.push_str("| `--config <PATH>` | Path to the configuration file. |\n");
    s.push_str("| `--verbose`, `-v` | Enable verbose output. |\n");
    s.push_str("| `--json` | Emit machine-readable JSON/NDJSON instead of the human view. |\n\n");
    s.push_str(
        "`--json` is the agent-first interface: every `cs` command honours it, so a worker \
or external orchestrator parses structured output rather than scraping the terminal render.\n\n",
    );
    s.push_str("## Command groups\n\n");
    s.push_str("The command reference is split by role:\n\n");
    for group in command_group_layout() {
        let _ = writeln!(
            s,
            "- [{title}](./{slug}.md)",
            title = group.title,
            slug = group.slug
        );
    }
    s.push('\n');
    ReferencePage {
        filename: "overview.md".to_owned(),
        content: s,
    }
}

/// Render one group page: heading, banner, then each allowlisted command
/// rendered from the clap tree. `Synthetic` slots (e.g. `guide`) are
/// skipped — they are not real clap subcommands and have no `--help` to
/// project. A `Derived` slot whose name is not found is skipped too; the
/// golden test catches such a typo because the committed page then loses a
/// section.
fn group_page(
    root: &clap::Command,
    title: &str,
    slug: &str,
    slots: &[CommandSlot],
) -> ReferencePage {
    let mut s = String::new();
    s.push_str(GENERATED_NOTICE);
    let _ = write!(s, "\n\n# {title} commands\n\n");
    s.push_str(VOCAB_BANNER);
    s.push_str("\n\n");
    for slot in slots {
        if let CommandSlot::Derived(name) = *slot {
            if let Some(sub) = root.find_subcommand(name) {
                s.push_str(&render_command_fragment(sub));
                s.push('\n');
            }
        }
    }
    ReferencePage {
        filename: format!("{slug}.md"),
        content: s,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root() -> clap::Command {
        crate::build_cli()
    }

    #[test]
    fn overview_and_one_page_per_group_are_generated() {
        let pages = reference_pages(&root());
        // overview + 7 groups.
        assert_eq!(pages.len(), 1 + command_group_layout().len());
        assert_eq!(pages[0].filename, "overview.md");
        let names: Vec<&str> = pages.iter().map(|p| p.filename.as_str()).collect();
        assert!(names.contains(&"lifecycle.md"));
        assert!(names.contains(&"observability.md"));
        assert!(names.contains(&"integrity.md"));
    }

    #[test]
    fn every_page_carries_the_vocabulary_banner() {
        for page in reference_pages(&root()) {
            assert!(
                page.content.contains("The physics vocabulary"),
                "page {} is missing the vocabulary banner",
                page.filename
            );
        }
    }

    #[test]
    fn hidden_verbs_never_appear_in_the_reference() {
        let joined: String = reference_pages(&root())
            .iter()
            .map(|p| p.content.clone())
            .collect();
        // A sample of the hidden internal verbs (ADR-B1′ §5.2 / R2).
        for hidden in ["## `cs sensorium`", "## `cs cluster`", "## `cs vllm-mlx`"] {
            assert!(
                !joined.contains(hidden),
                "hidden verb leaked into the Reference: {hidden}"
            );
        }
    }

    #[test]
    fn commands_are_prefixed_with_cs() {
        let lifecycle = reference_pages(&root())
            .into_iter()
            .find(|p| p.filename == "lifecycle.md")
            .expect("lifecycle page");
        assert!(lifecycle.content.contains("## `cs nucleate`"));
    }
}
