# typed: false
# frozen_string_literal: true

# Cosmon CLI — stateless agent-fleet orchestrator.
#
# This formula is generated by scripts/release/render-brew-formula.sh in the
# cosmon repo and pushed to the tap by the signed release pipeline
# (.github/workflows/release.yml). Do not edit by hand — your change will be
# overwritten on the next release. The checked-in copy at
# packaging/homebrew-tap/Formula/cosmon.rb is the SAME renderer's output with
# placeholder digests; the real per-target sha256 values are injected from the
# build artifacts at release time. render-brew-formula.test.sh keeps the two
# in lockstep.
#
# The tarballs are signed (cosign keyless) and anchored in the public Rekor
# transparency log. brew verifies the sha256 below at install time; to verify
# the cosign signature after install, see:
#   https://github.com/noogram/cosmon/blob/main/docs/guides/release-verification.md
class Cosmon < Formula
  desc "Stateless CLI giving AI coding agents identity, lifecycle, and crash-recovery"
  homepage "https://github.com/noogram/cosmon"
  version "0.1.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/noogram/cosmon/releases/download/v0.1.0/cosmon-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/noogram/cosmon/releases/download/v0.1.0/cosmon-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "1111111111111111111111111111111111111111111111111111111111111111"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/noogram/cosmon/releases/download/v0.1.0/cosmon-0.1.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "3333333333333333333333333333333333333333333333333333333333333333"
    end
    on_intel do
      url "https://github.com/noogram/cosmon/releases/download/v0.1.0/cosmon-0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2222222222222222222222222222222222222222222222222222222222222222"
    end
  end

  def install
    # The client tarball carries both laptop tools: the `cs` pilot and the
    # `cosmon-remote` connector (the thin client the remote-service how-to
    # drives). Installing both means one `brew install` equips a user to pilot
    # cosmon locally or against a remote fente.
    bin.install "cs"
    bin.install "cosmon-remote"
  end

  test do
    assert_match "cs ", shell_output("#{bin}/cs --version")
    assert_match "cosmon-remote ", shell_output("#{bin}/cosmon-remote --version")
  end
end
