# typed: false
# frozen_string_literal: true

# Cosmon CLI — stateless agent-fleet orchestrator.
#
# This formula is generated by scripts/release/render-brew-formula.sh in the
# cosmon repo and pushed here by the signed release pipeline
# (.github/workflows/release.yml). Do not edit by hand — your change will be
# overwritten on the next release.
#
# The tarballs are signed (cosign keyless) and anchored in the public Rekor
# transparency log. brew verifies the sha256 below at install time; to verify
# the cosign signature after install, see:
#   https://github.com/noogram/cosmon/blob/main/docs/guides/release-verification.md
class Cosmon < Formula
  desc "Stateless CLI giving AI coding agents identity, lifecycle, and crash-recovery"
  homepage "https://github.com/noogram/cosmon"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/noogram/cosmon/releases/download/v0.1.0/cosmon-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/noogram/cosmon/releases/download/v0.1.0/cosmon-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "1111111111111111111111111111111111111111111111111111111111111111"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/noogram/cosmon/releases/download/v0.1.0/cosmon-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2222222222222222222222222222222222222222222222222222222222222222"
    end
  end

  def install
    bin.install "cs"
  end

  test do
    assert_match "cs ", shell_output("#{bin}/cs --version")
  end
end
