#!/usr/bin/env bash
# Render the Homebrew formula for the cosmon client tarball.
#
# WHY this exists: the release pipeline (.github/workflows/release.yml, the
# `render` job) needs a single, testable source of truth for the tap formula so
# that a release NEVER pushes a hand-edited, drifted, or half-filled formula.
# The checked-in copy at packaging/homebrew-tap/Formula/cosmon.rb is this
# script's output rendered with PLACEHOLDER digests; at release time the same
# script is re-run with the real per-target sha256 values (read from the build
# artifacts) and the result is pushed to the tap. render-brew-formula.test.sh
# locks the checked-in copy to this script's placeholder output, so the two can
# never silently diverge.
#
# The formula serves every triple the release matrix builds and install.sh
# resolves: macOS arm64/x86_64 and Linux arm64/x86_64 (musl). Keeping the four
# stanzas here in lockstep with release.yml's matrix is enforced by the
# install-lint `triples` job (brew ⊆ installer).
#
# Usage:
#   render-brew-formula.sh \
#     --version 0.1.0 --owner noogram \
#     --sha-arm-macos <hex> --sha-x86-macos <hex> \
#     --sha-arm-linux <hex> --sha-x86-linux <hex>
#
# All six flags are required. Each sha value must be 64 lowercase hex chars.
# The rendered formula is written to stdout.
set -euo pipefail

version=""
owner=""
sha_arm_macos=""
sha_x86_macos=""
sha_arm_linux=""
sha_x86_linux=""

die() {
  echo "render-brew-formula: $*" >&2
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    --version)       version="${2:-}"; shift 2 ;;
    --owner)         owner="${2:-}"; shift 2 ;;
    --sha-arm-macos) sha_arm_macos="${2:-}"; shift 2 ;;
    --sha-x86-macos) sha_x86_macos="${2:-}"; shift 2 ;;
    --sha-arm-linux) sha_arm_linux="${2:-}"; shift 2 ;;
    --sha-x86-linux) sha_x86_linux="${2:-}"; shift 2 ;;
    -h|--help)
      sed -n '2,30p' "$0"
      exit 0
      ;;
    *) die "unknown argument: $1" ;;
  esac
done

[ -n "$version" ] || die "--version is required"
[ -n "$owner" ]   || die "--owner is required"

# Each sha must be present and shaped like a real sha256. This is a shape check,
# not a placeholder check — the release pipeline passes real digests; the
# checked-in snapshot passes deterministic placeholders that still match /^[0-9a-f]{64}$/.
validate_sha() {
  # $1 = flag name, $2 = value
  case "$2" in
    "") die "$1 is required" ;;
  esac
  case "$2" in
    *[!0-9a-f]*) die "$1 must be 64 lowercase hex chars, got: $2" ;;
  esac
  [ "${#2}" -eq 64 ] || die "$1 must be 64 lowercase hex chars, got length ${#2}"
}
validate_sha --sha-arm-macos "$sha_arm_macos"
validate_sha --sha-x86-macos "$sha_x86_macos"
validate_sha --sha-arm-linux "$sha_arm_linux"
validate_sha --sha-x86-linux "$sha_x86_linux"

base="https://github.com/${owner}/cosmon/releases/download/v${version}"

cat <<RUBY
# typed: false
# frozen_string_literal: true

# Cosmon CLI — stateless agent-fleet orchestrator.
#
# This formula is generated by scripts/release/render-brew-formula.sh in the
# cosmon repo and pushed to the tap by the signed release pipeline
# (.github/workflows/release.yml). Do not edit by hand — your change will be
# overwritten on the next release. The checked-in copy at
# packaging/homebrew-tap/Formula/cosmon.rb is the SAME renderer's output with
# placeholder digests; the real per-target sha256 values are injected from the
# build artifacts at release time. render-brew-formula.test.sh keeps the two
# in lockstep.
#
# The tarballs are signed (cosign keyless) and anchored in the public Rekor
# transparency log. brew verifies the sha256 below at install time; to verify
# the cosign signature after install, see:
#   https://github.com/${owner}/cosmon/blob/main/docs/guides/release-verification.md
class Cosmon < Formula
  desc "Stateless CLI giving AI coding agents identity, lifecycle, and crash-recovery"
  homepage "https://github.com/${owner}/cosmon"
  version "${version}"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "${base}/cosmon-${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${sha_arm_macos}"
    end
    on_intel do
      url "${base}/cosmon-${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${sha_x86_macos}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/cosmon-${version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${sha_arm_linux}"
    end
    on_intel do
      url "${base}/cosmon-${version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${sha_x86_linux}"
    end
  end

  def install
    # The client tarball carries both laptop tools: the \`cs\` pilot and the
    # \`cosmon-remote\` connector (the thin client the remote-service how-to
    # drives). Installing both means one \`brew install\` equips a user to pilot
    # cosmon locally or against a remote fente.
    bin.install "cs"
    bin.install "cosmon-remote"
  end

  test do
    assert_match "cs ", shell_output("#{bin}/cs --version")
    assert_match "cosmon-remote ", shell_output("#{bin}/cosmon-remote --version")
  end
end
RUBY
