// SPDX-License-Identifier: Apache-2.0

//! Core domain types for session measurement.
//!
//! These types represent the parsed, structured view of Claude Code session
//! logs. [`Turn`] captures a single assistant response with its token breakdown.
//! [`SessionLog`] is the complete parsed session. [`SessionPath`] is a lightweight
//! handle discovered on the filesystem before parsing.

use std::path::PathBuf;

use crate::energy::{SessionId, TokenCount};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A single assistant turn with token breakdown.
///
/// Mirrors the Claude API `usage` block: four orthogonal token counters
/// that together describe how much energy a single response consumed.
/// The cache split (creation vs. read) is critical for cost estimation
/// because cache reads are 90% cheaper than fresh input.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Turn {
    /// Sequence number within the session (0-indexed).
    pub index: usize,
    /// When this turn occurred.
    pub timestamp: DateTime<Utc>,
    /// The model that produced this turn (e.g. `"claude-opus-4-6"`).
    pub model: Option<String>,
    /// Fresh input tokens (not from cache).
    pub input_tokens: TokenCount,
    /// Tokens written to create new cache entries.
    pub cache_creation_input_tokens: TokenCount,
    /// Tokens read from existing cache (cheap).
    pub cache_read_input_tokens: TokenCount,
    /// Output tokens generated by the model.
    pub output_tokens: TokenCount,
}

impl Turn {
    /// Total input tokens (fresh + cache creation + cache read).
    #[must_use]
    pub fn total_input(&self) -> TokenCount {
        self.input_tokens + self.cache_creation_input_tokens + self.cache_read_input_tokens
    }

    /// Total tokens across input and output.
    #[must_use]
    pub fn total_tokens(&self) -> TokenCount {
        self.total_input() + self.output_tokens
    }
}

/// A discovered session log on the filesystem (not yet parsed).
///
/// Discovery is cheap (stat files); parsing is expensive (read every line).
/// This two-phase API lets callers filter by project or date before committing
/// to a full parse.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionPath {
    /// The filesystem path to the JSONL file.
    pub path: PathBuf,
    /// Session ID extracted from the filename.
    pub session_id: SessionId,
    /// Encoded project directory name (e.g. `"-Users-you-cosmon"`).
    pub project: String,
}

/// A fully parsed session log.
///
/// Contains all assistant turns with their token usage, plus session-level
/// metadata extracted from the JSONL header lines.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionLog {
    /// The session identifier (UUID).
    pub session_id: SessionId,
    /// Encoded project directory name.
    pub project: String,
    /// Human-readable session slug (e.g. `"purring-hugging-otter"`).
    pub slug: Option<String>,
    /// Timestamp of the first turn.
    pub start_time: Option<DateTime<Utc>>,
    /// Timestamp of the last turn.
    pub end_time: Option<DateTime<Utc>>,
    /// All assistant turns with token usage, in chronological order.
    pub turns: Vec<Turn>,
    /// Total JSONL lines processed (including non-assistant lines).
    pub total_lines: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_turn(index: usize, input: u64, output: u64) -> Turn {
        Turn {
            index,
            timestamp: Utc::now(),
            model: Some("claude-opus-4-6".to_string()),
            input_tokens: TokenCount::new(input),
            cache_creation_input_tokens: TokenCount::new(100),
            cache_read_input_tokens: TokenCount::new(5000),
            output_tokens: TokenCount::new(output),
        }
    }

    #[test]
    fn test_turn_total_input() {
        let turn = sample_turn(0, 50, 200);
        // 50 + 100 + 5000 = 5150
        assert_eq!(turn.total_input(), TokenCount::new(5150));
    }

    #[test]
    fn test_turn_total_tokens() {
        let turn = sample_turn(0, 50, 200);
        // 5150 + 200 = 5350
        assert_eq!(turn.total_tokens(), TokenCount::new(5350));
    }
}
