// SPDX-License-Identifier: AGPL-3.0-only

//! `cosmon-remote` build script — folds the §8p surface canon
//! (`crates/cosmon-rpp-adapter/data/surface_events.txt`) into the
//! compile-time route table the delivered tenant binary dials.
//!
//! Before this fold the binary carried its own copy of every route as
//! a string literal in `client.rs` — three parallel hand
//! copies, the bug class that left `molecule freeze`/`thaw` silently
//! broken against the post-fusion adapter. The route tuple now has ONE
//! declaration (the canon line); the client refers to it by generated
//! const. Removing a route from the canon is a compile error here, not
//! a 410 in a tenant's terminal.
//!
//! Workspace-relative read: same coupling as `cosmon-thin-cli/build.rs`
//! (the crate is not published standalone); the shared parser is
//! `cosmon-surface-canon` — one parser, one source, three folds.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use cosmon_surface_canon::{parse_canon, CanonEvent};

const DATA_FILE: &str = "../cosmon-rpp-adapter/data/surface_events.txt";
const GENERATED_FILE: &str = "canon_surface_generated.rs";

fn main() {
    println!("cargo:rerun-if-changed={DATA_FILE}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let data_path = manifest_dir.join(DATA_FILE);
    let raw = fs::read_to_string(&data_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", data_path.display()));

    let events = parse_canon(&raw, DATA_FILE).unwrap_or_else(|err| panic!("{err}"));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join(GENERATED_FILE);
    fs::write(&out_path, render(&events))
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

/// Mechanical const name for one canon row: `METHOD` + path with every
/// non-alphanumeric run collapsed to `_`, placeholder braces dropped.
/// `POST /v1/molecules/{id}/tackle` → `POST_V1_MOLECULES_ID_TACKLE`.
/// The name is derived, never hand-chosen — it cannot drift from the
/// row, and a removed row removes the const (compile error at every
/// consumer).
fn const_name(method: &str, path: &str) -> String {
    let mut out = String::from(method);
    let mut last_underscore = false;
    for ch in path.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
            last_underscore = false;
        } else if ch == '{' || ch == '}' {
            // Placeholder braces vanish; the name keeps the segment.
        } else if !last_underscore {
            out.push('_');
            last_underscore = true;
        }
    }
    out.trim_end_matches('_').to_owned()
}

fn render(events: &[CanonEvent]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by crates/cosmon-remote/build.rs from \
         crates/cosmon-rpp-adapter/data/surface_events.txt.\n",
    );
    out.push_str("// DO NOT EDIT — append to the data file instead.\n\n");

    out.push_str("/// Every route of the §8p frozen surface, canon order.\n");
    out.push_str("pub static CANON: &[CanonRoute] = &[\n");
    for ev in events {
        let (method, path) = ev
            .method_path
            .split_once(' ')
            .expect("parse_canon guarantees `METHOD PATH` shape");
        writeln!(
            out,
            "    CanonRoute {{ method: {method:?}, path: {path:?}, scope: {:?}, \
             exposure: {}, blurb: {:?} }},",
            ev.scope,
            ev.exposure.as_variant(),
            ev.blurb,
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    for (i, ev) in events.iter().enumerate() {
        let (method, path) = ev.method_path.split_once(' ').expect("validated above");
        writeln!(
            out,
            "/// Canon row {i}: `{} {}`.\npub const {}: &CanonRoute = &CANON[{i}];",
            method,
            path,
            const_name(method, path),
        )
        .unwrap();
    }
    out
}
