// SPDX-License-Identifier: AGPL-3.0-only

//! Operator-provisioned collaboration bindings and their admission decision.
//!
//! The cross-machine collaboration contract
//! (`docs/specs/cross-machine-collaboration.md`, §2) needs a fact that the
//! OIDC admission boundary cannot supply: *which* work seat or pilot mission a
//! remote caller may act for. A tenant-wide token proves who the caller is;
//! it does not say that the caller occupies seat `reviewer` of one work.
//!
//! This module holds that fact and the pure decision over it:
//!
//! - a [`CollaborationBinding`] ties one exact admitted identity
//!   (issuer, subject, audience, tenant) to one [`CollaborationCapability`]
//!   through one [`AttachmentId`]. Each attachment carries its own revocable
//!   proof; the host stores only its [`ProofVerifier`];
//! - [`admit`] checks a request against the current [`BindingSet`] and returns
//!   an [`AdmittedCollaborator`] whose seat or mission comes from the binding,
//!   never from the request;
//! - [`recheck`] repeats the binding part at commit time, so revocation and an
//!   effect have an auditable order.
//!
//! The module performs no I/O. Proof bytes are generated by the provisioning
//! adapter, and bindings are loaded by the state crate.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use chrono::{DateTime, Utc};
use cosmon_hash::Hash;
use serde::{Deserialize, Serialize};

use crate::advisory_attempt::AdvisorySeatId;
use crate::id::MoleculeId;
use crate::work_message::{AdmittedWorkCaller, SenderEvidence};

/// Current schema of a persisted [`CollaborationBinding`].
pub const BINDING_SCHEMA_VERSION: u32 = 1;

/// Domain tag mixed into every proof digest, so a verifier can never be
/// confused with the digest of the same bytes used elsewhere.
const PROOF_DOMAIN: &str = "cosmon-collaboration-attachment-proof-v1";

/// Length in bytes of the secret behind an [`AttachmentProof`].
pub const PROOF_SECRET_BYTES: usize = 32;

/// Prefix of the textual form of an [`AttachmentProof`].
const PROOF_PREFIX: &str = "cap1-";

/// Maximum length of a device label, which is display metadata only.
pub const MAX_LABEL_BYTES: usize = 120;

fn to_hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes.iter().fold(String::new(), |mut out, byte| {
        let _ = write!(out, "{byte:02x}");
        out
    })
}

/// Refusal of a binding provisioning request or a malformed identifier.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum BindingSpecError {
    /// An identifier is empty, overlong or contains unsafe characters.
    #[error("invalid {kind}: {value:?}")]
    InvalidIdentifier {
        /// Kind of identifier.
        kind: &'static str,
        /// Rejected value.
        value: String,
    },
    /// An identity component is empty or overlong.
    #[error("invalid identity component {field}")]
    InvalidIdentity {
        /// Name of the offending component.
        field: &'static str,
    },
    /// A scope string is not one of the collaboration scopes.
    #[error("unknown collaboration scope {0:?}")]
    UnknownScope(String),
    /// No scope was granted; a binding without a scope grants nothing.
    #[error("a binding must grant at least one collaboration scope")]
    NoScope,
    /// A scope belongs to the other capability family.
    #[error("scope {scope} does not apply to a {capability} binding")]
    ScopeOutsideCapability {
        /// Offending scope.
        scope: CollaborationScope,
        /// Capability family of the binding.
        capability: &'static str,
    },
    /// The device label is too long or contains control characters.
    #[error("device label must be at most {MAX_LABEL_BYTES} printable bytes")]
    InvalidLabel,
    /// The textual proof does not have the expected shape.
    #[error("malformed attachment proof")]
    MalformedProof,
}

macro_rules! binding_id {
    ($(#[$meta:meta])* $name:ident, $kind:literal, $prefix:literal) => {
        $(#[$meta])*
        #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
        #[serde(try_from = "String", into = "String")]
        pub struct $name(String);

        impl $name {
            /// Validate an identifier: the fixed prefix followed by 16 to 64
            /// lowercase hexadecimal characters. The shape keeps it safe as a
            /// file name and unambiguous in logs.
            ///
            /// # Errors
            /// Returns [`BindingSpecError::InvalidIdentifier`] otherwise.
            pub fn new(value: impl Into<String>) -> Result<Self, BindingSpecError> {
                let value = value.into();
                let valid = value.strip_prefix($prefix).is_some_and(|hex| {
                    (16..=64).contains(&hex.len())
                        && hex.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
                });
                if valid {
                    Ok(Self(value))
                } else {
                    Err(BindingSpecError::InvalidIdentifier { kind: $kind, value })
                }
            }

            /// Build the identifier from random bytes chosen by an adapter.
            #[must_use]
            pub fn from_random(bytes: [u8; 8]) -> Self {
                let hex = to_hex(&bytes);
                Self(format!("{}{hex}", $prefix))
            }

            /// Borrow the validated identifier.
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl TryFrom<String> for $name {
            type Error = BindingSpecError;

            fn try_from(value: String) -> Result<Self, Self::Error> {
                Self::new(value)
            }
        }

        impl From<$name> for String {
            fn from(value: $name) -> Self {
                value.0
            }
        }
    };
}

binding_id!(
    /// Host-issued identifier of one collaboration binding record.
    BindingId,
    "binding id",
    "cb-"
);

binding_id!(
    /// Host-issued Cosmon attachment identity. Two attachments of one user
    /// are distinct values with distinct proofs; knowing an attachment ID
    /// without its proof admits nothing.
    AttachmentId,
    "attachment id",
    "att-"
);

/// Monotone revision of one binding. Any change to the binding, including
/// revocation, increases it, so an admission taken at revision `n` can be
/// refused at commit once the record moved on.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct BindingRevision(u64);

impl BindingRevision {
    /// Revision of a freshly provisioned binding.
    pub const INITIAL: Self = Self(1);

    /// Wrap a raw revision number.
    #[must_use]
    pub fn from_u64(value: u64) -> Self {
        Self(value)
    }

    /// Raw revision number.
    #[must_use]
    pub fn as_u64(self) -> u64 {
        self.0
    }

    /// The next revision.
    #[must_use]
    pub fn next(self) -> Self {
        Self(self.0.saturating_add(1))
    }
}

impl fmt::Display for BindingRevision {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Exact identity selected by token validation and the audience-pinned tenant
/// binding. Every component is compared byte for byte; there is no wildcard.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AdmittedIdentity {
    issuer: String,
    subject: String,
    audience: String,
    tenant: String,
}

impl AdmittedIdentity {
    /// Build an identity from validated components.
    ///
    /// # Errors
    /// Refuses an empty component, one over 512 bytes, or one containing a
    /// control character.
    pub fn new(
        issuer: impl Into<String>,
        subject: impl Into<String>,
        audience: impl Into<String>,
        tenant: impl Into<String>,
    ) -> Result<Self, BindingSpecError> {
        let identity = Self {
            issuer: issuer.into(),
            subject: subject.into(),
            audience: audience.into(),
            tenant: tenant.into(),
        };
        identity.validate()?;
        Ok(identity)
    }

    fn validate(&self) -> Result<(), BindingSpecError> {
        for (field, value) in [
            ("issuer", &self.issuer),
            ("subject", &self.subject),
            ("audience", &self.audience),
            ("tenant", &self.tenant),
        ] {
            if value.is_empty() || value.len() > 512 || value.chars().any(char::is_control) {
                return Err(BindingSpecError::InvalidIdentity { field });
            }
        }
        Ok(())
    }

    /// Token issuer.
    #[must_use]
    pub fn issuer(&self) -> &str {
        &self.issuer
    }

    /// Token subject.
    #[must_use]
    pub fn subject(&self) -> &str {
        &self.subject
    }

    /// Token audience.
    #[must_use]
    pub fn audience(&self) -> &str {
        &self.audience
    }

    /// Tenant selected by the audience-pinned identity binding.
    #[must_use]
    pub fn tenant(&self) -> &str {
        &self.tenant
    }
}

/// The four collaboration scopes of the contract (§3). None implies a binding
/// or membership; each only names what an existing binding may be used for.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub enum CollaborationScope {
    /// `cosmon:work:read`.
    WorkRead,
    /// `cosmon:work:write`, which implies `cosmon:work:read`.
    WorkWrite,
    /// `cosmon:sessions:read`.
    SessionsRead,
    /// `cosmon:sessions:write`, which implies `cosmon:sessions:read`.
    SessionsWrite,
}

impl CollaborationScope {
    /// Every scope, in catalog order.
    pub const ALL: [Self; 4] = [
        Self::WorkRead,
        Self::WorkWrite,
        Self::SessionsRead,
        Self::SessionsWrite,
    ];

    /// Wire string of the scope.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::WorkRead => "cosmon:work:read",
            Self::WorkWrite => "cosmon:work:write",
            Self::SessionsRead => "cosmon:sessions:read",
            Self::SessionsWrite => "cosmon:sessions:write",
        }
    }

    /// Parse an exact wire string.
    ///
    /// # Errors
    /// Returns [`BindingSpecError::UnknownScope`] for any other string.
    pub fn parse(value: &str) -> Result<Self, BindingSpecError> {
        Self::ALL
            .into_iter()
            .find(|scope| scope.as_str() == value)
            .ok_or_else(|| BindingSpecError::UnknownScope(value.to_owned()))
    }

    /// Whether holding `self` satisfies a requirement for `required`.
    #[must_use]
    pub fn satisfies(self, required: Self) -> bool {
        self == required
            || matches!(
                (self, required),
                (Self::WorkWrite, Self::WorkRead) | (Self::SessionsWrite, Self::SessionsRead)
            )
    }

    fn is_work(self) -> bool {
        matches!(self, Self::WorkRead | Self::WorkWrite)
    }
}

impl fmt::Display for CollaborationScope {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<String> for CollaborationScope {
    type Error = BindingSpecError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(&value)
    }
}

impl From<CollaborationScope> for String {
    fn from(value: CollaborationScope) -> Self {
        value.as_str().to_owned()
    }
}

/// What one binding lets its attachment act as.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum CollaborationCapability {
    /// One seat of the work owned by `owner`.
    WorkSeat {
        /// Molecule owning the declared work.
        owner: MoleculeId,
        /// Seat the attachment sends and acknowledges as.
        seat: AdvisorySeatId,
    },
    /// One pilot attachment of `mission`.
    PilotMission {
        /// Mission whose pilot surface the attachment joins.
        mission: MoleculeId,
    },
}

impl CollaborationCapability {
    fn family(&self) -> &'static str {
        match self {
            Self::WorkSeat { .. } => "work seat",
            Self::PilotMission { .. } => "pilot mission",
        }
    }

    fn admits_scope(&self, scope: CollaborationScope) -> bool {
        match self {
            Self::WorkSeat { .. } => scope.is_work(),
            Self::PilotMission { .. } => !scope.is_work(),
        }
    }

    fn covers(&self, target: &CollaborationTarget) -> bool {
        match (self, target) {
            (Self::WorkSeat { owner, .. }, CollaborationTarget::Work { owner: wanted }) => {
                owner == wanted
            }
            (Self::PilotMission { mission }, CollaborationTarget::Mission { mission: wanted }) => {
                mission == wanted
            }
            _ => false,
        }
    }
}

/// The resource a request addresses. It names a work or a mission, never a
/// seat: the seat is a property of the binding.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CollaborationTarget {
    /// A declared work, by its owning molecule.
    Work {
        /// Owning molecule.
        owner: MoleculeId,
    },
    /// A pilot mission.
    Mission {
        /// Mission root.
        mission: MoleculeId,
    },
}

/// Private attachment proof presented by a client alongside its OIDC token.
///
/// The textual form is `cap1-` followed by 64 hexadecimal characters. The type
/// has no `Clone`, `Display` or `Serialize`, and its `Debug` is redacted, so a
/// stray format or record cannot carry it.
pub struct AttachmentProof(secrecy::SecretString);

impl AttachmentProof {
    /// Encode freshly generated secret bytes.
    #[must_use]
    pub fn from_secret_bytes(bytes: [u8; PROOF_SECRET_BYTES]) -> Self {
        let hex = to_hex(&bytes);
        Self(secrecy::SecretString::new(format!("{PROOF_PREFIX}{hex}")))
    }

    /// Parse the textual form received from a client.
    ///
    /// # Errors
    /// Returns [`BindingSpecError::MalformedProof`] for any other shape.
    pub fn parse(text: &str) -> Result<Self, BindingSpecError> {
        let text = text.trim();
        let valid = text.strip_prefix(PROOF_PREFIX).is_some_and(|hex| {
            hex.len() == PROOF_SECRET_BYTES * 2 && hex.bytes().all(|b| b.is_ascii_hexdigit())
        });
        if valid {
            Ok(Self(secrecy::SecretString::new(text.to_ascii_lowercase())))
        } else {
            Err(BindingSpecError::MalformedProof)
        }
    }

    /// Plaintext for the one legitimate use: handing it to the operator once
    /// at provisioning or presenting it on the wire.
    #[must_use]
    pub fn expose_secret(&self) -> &str {
        use secrecy::ExposeSecret;
        self.0.expose_secret()
    }

    /// Verifier the host keeps instead of the proof.
    #[must_use]
    pub fn verifier(&self) -> ProofVerifier {
        let material = format!("{PROOF_DOMAIN}\u{1f}{}", self.expose_secret());
        ProofVerifier(Hash::of_bytes(material.as_bytes()))
    }
}

impl fmt::Debug for AttachmentProof {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("AttachmentProof(***)")
    }
}

/// Domain-separated BLAKE3 digest of an attachment proof. The proof has 256
/// bits of entropy, so the verifier reveals nothing usable and an equality
/// comparison of digests leaks nothing an attacker can steer.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ProofVerifier(Hash);

impl ProofVerifier {
    /// Whether `proof` is the secret this verifier was made from.
    #[must_use]
    pub fn matches(&self, proof: &AttachmentProof) -> bool {
        proof.verifier() == *self
    }
}

/// One operator-provisioned binding record.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CollaborationBinding {
    /// Record schema; a newer schema is refused on read.
    pub schema_version: u32,
    /// Host-issued binding identifier.
    pub id: BindingId,
    /// Exact admitted identity allowed to use the attachment.
    pub identity: AdmittedIdentity,
    /// What the attachment may act as.
    pub capability: CollaborationCapability,
    /// Host-issued attachment identity.
    pub attachment: AttachmentId,
    /// Verifier of the attachment proof; the proof itself is never stored.
    pub verifier: ProofVerifier,
    /// Scopes this binding can be used for.
    pub scopes: BTreeSet<CollaborationScope>,
    /// Current revision.
    pub revision: BindingRevision,
    /// Display metadata only; never consulted by admission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Provisioning time.
    pub created_at: DateTime<Utc>,
    /// Revocation time; a revoked binding admits nothing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
}

/// Operator input for a new binding. Identifiers and the proof are chosen by
/// the provisioning adapter, never by the operator or a remote caller.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BindingSpec {
    /// Identity to bind.
    pub identity: AdmittedIdentity,
    /// Capability to grant.
    pub capability: CollaborationCapability,
    /// Scopes to grant; must be non-empty and match the capability family.
    pub scopes: BTreeSet<CollaborationScope>,
    /// Optional display label.
    pub label: Option<String>,
}

impl CollaborationBinding {
    /// Build a fresh binding at [`BindingRevision::INITIAL`].
    ///
    /// # Errors
    /// Refuses an empty scope set, a scope of the other capability family, an
    /// invalid identity or an invalid label.
    pub fn provision(
        spec: BindingSpec,
        id: BindingId,
        attachment: AttachmentId,
        proof: &AttachmentProof,
        created_at: DateTime<Utc>,
    ) -> Result<Self, BindingSpecError> {
        let binding = Self {
            schema_version: BINDING_SCHEMA_VERSION,
            id,
            identity: spec.identity,
            capability: spec.capability,
            attachment,
            verifier: proof.verifier(),
            scopes: spec.scopes,
            revision: BindingRevision::INITIAL,
            label: spec.label,
            created_at,
            revoked_at: None,
        };
        binding.validate()?;
        Ok(binding)
    }

    /// Check the invariants a stored record must satisfy.
    ///
    /// # Errors
    /// Returns the first violated invariant.
    pub fn validate(&self) -> Result<(), BindingSpecError> {
        self.identity.validate()?;
        if self.scopes.is_empty() {
            return Err(BindingSpecError::NoScope);
        }
        if let Some(scope) = self
            .scopes
            .iter()
            .copied()
            .find(|scope| !self.capability.admits_scope(*scope))
        {
            return Err(BindingSpecError::ScopeOutsideCapability {
                scope,
                capability: self.capability.family(),
            });
        }
        if let Some(label) = &self.label {
            if label.len() > MAX_LABEL_BYTES || label.chars().any(char::is_control) {
                return Err(BindingSpecError::InvalidLabel);
            }
        }
        Ok(())
    }

    /// Return the revoked successor of this record. Revoking an already
    /// revoked binding returns it unchanged.
    #[must_use]
    pub fn revoked(&self, at: DateTime<Utc>) -> Self {
        if self.revoked_at.is_some() {
            return self.clone();
        }
        Self {
            revision: self.revision.next(),
            revoked_at: Some(at),
            ..self.clone()
        }
    }

    /// Whether the binding still admits requests.
    #[must_use]
    pub fn is_active(&self) -> bool {
        self.revoked_at.is_none()
    }

    fn grants(&self, required: CollaborationScope) -> bool {
        self.scopes.iter().any(|held| held.satisfies(required))
    }
}

/// Every binding the host currently holds, indexed by attachment.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct BindingSet {
    by_attachment: BTreeMap<AttachmentId, CollaborationBinding>,
}

/// A loaded binding set violates uniqueness; admission must fail closed.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
pub enum BindingSetError {
    /// Two records share a binding or attachment identifier.
    #[error("duplicate {kind} {value}")]
    Duplicate {
        /// Kind of duplicated identifier.
        kind: &'static str,
        /// Duplicated value.
        value: String,
    },
    /// A record fails its own invariants.
    #[error("binding {id} is invalid: {source}")]
    Invalid {
        /// Offending binding.
        id: BindingId,
        /// Violated invariant.
        source: BindingSpecError,
    },
}

impl BindingSet {
    /// Index `bindings`, refusing duplicates and invalid records.
    ///
    /// # Errors
    /// Returns [`BindingSetError`] when the records cannot be trusted as a set.
    pub fn new(
        bindings: impl IntoIterator<Item = CollaborationBinding>,
    ) -> Result<Self, BindingSetError> {
        let mut ids = BTreeSet::new();
        let mut by_attachment = BTreeMap::new();
        for binding in bindings {
            binding
                .validate()
                .map_err(|source| BindingSetError::Invalid {
                    id: binding.id.clone(),
                    source,
                })?;
            if !ids.insert(binding.id.clone()) {
                return Err(BindingSetError::Duplicate {
                    kind: "binding id",
                    value: binding.id.to_string(),
                });
            }
            let attachment = binding.attachment.clone();
            if by_attachment.insert(attachment.clone(), binding).is_some() {
                return Err(BindingSetError::Duplicate {
                    kind: "attachment id",
                    value: attachment.to_string(),
                });
            }
        }
        Ok(Self { by_attachment })
    }

    /// Bindings in attachment order.
    pub fn iter(&self) -> impl Iterator<Item = &CollaborationBinding> {
        self.by_attachment.values()
    }

    /// Number of bindings, active or revoked.
    #[must_use]
    pub fn len(&self) -> usize {
        self.by_attachment.len()
    }

    /// Whether the host holds no binding at all.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.by_attachment.is_empty()
    }
}

/// Everything a boundary presents for one admission decision. Every field is
/// either a validated token fact or a value the decision checks; none of them
/// selects the seat.
#[derive(Debug)]
pub struct AdmissionRequest<'a> {
    /// Identity selected by token validation.
    pub identity: &'a AdmittedIdentity,
    /// Attachment the client claims to hold.
    pub attachment: &'a AttachmentId,
    /// Proof of that attachment.
    pub proof: &'a AttachmentProof,
    /// Work or mission addressed by the route.
    pub target: &'a CollaborationTarget,
    /// Scope the route requires.
    pub required: CollaborationScope,
}

/// Stable refusal of a collaboration admission. Codes are those of the
/// contract's error table (§6); every refusal there is an HTTP 403.
#[derive(Clone, Copy, Debug, PartialEq, Eq, thiserror::Error)]
pub enum CollaborationRefusal {
    /// No binding matches the identity, attachment, proof and target.
    #[error("no collaboration binding for this identity and target")]
    BindingMissing,
    /// The binding was revoked or moved past the admitted revision.
    #[error("the collaboration binding was revoked or changed")]
    BindingRevoked,
    /// The binding does not grant the route's scope.
    #[error("the collaboration binding lacks the required scope")]
    ScopeMissing,
}

impl CollaborationRefusal {
    /// Stable wire code from the contract's error table.
    #[must_use]
    pub fn code(self) -> &'static str {
        match self {
            Self::BindingMissing => "binding_missing",
            Self::BindingRevoked => "binding_revoked",
            Self::ScopeMissing => "scope_missing",
        }
    }
}

/// A caller admitted to one binding. Only [`admit`] constructs it, so its seat
/// or mission always comes from a stored binding.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdmittedCollaborator {
    binding: BindingId,
    revision: BindingRevision,
    attachment: AttachmentId,
    identity: AdmittedIdentity,
    capability: CollaborationCapability,
    scope: CollaborationScope,
}

impl AdmittedCollaborator {
    /// Binding that admitted the caller.
    #[must_use]
    pub fn binding(&self) -> &BindingId {
        &self.binding
    }

    /// Binding revision observed at admission.
    #[must_use]
    pub fn revision(&self) -> BindingRevision {
        self.revision
    }

    /// Attachment the caller proved.
    #[must_use]
    pub fn attachment(&self) -> &AttachmentId {
        &self.attachment
    }

    /// Identity the caller presented.
    #[must_use]
    pub fn identity(&self) -> &AdmittedIdentity {
        &self.identity
    }

    /// Capability taken from the binding.
    #[must_use]
    pub fn capability(&self) -> &CollaborationCapability {
        &self.capability
    }

    /// Scope the admission was checked for.
    #[must_use]
    pub fn scope(&self) -> CollaborationScope {
        self.scope
    }

    /// Work caller for the typed work operations, with the seat taken from
    /// the binding and [`SenderEvidence::AdmittedNonLocal`]. `None` for a
    /// pilot binding.
    #[must_use]
    pub fn work_caller(&self) -> Option<AdmittedWorkCaller> {
        match &self.capability {
            CollaborationCapability::WorkSeat { owner, seat } => Some(AdmittedWorkCaller::new(
                owner.clone(),
                seat.clone(),
                SenderEvidence::AdmittedNonLocal,
            )),
            CollaborationCapability::PilotMission { .. } => None,
        }
    }
}

/// Decide one collaboration admission against the current bindings.
///
/// The checks run in this order: binding lookup by attachment, exact identity,
/// target coverage, proof, revocation, scope. The first four all answer
/// [`CollaborationRefusal::BindingMissing`], so a caller cannot learn whether
/// an attachment exists, belongs to someone else or covers another target.
///
/// # Errors
/// Returns the refusal of the first failed check.
pub fn admit(
    bindings: &BindingSet,
    request: &AdmissionRequest<'_>,
) -> Result<AdmittedCollaborator, CollaborationRefusal> {
    let binding = bindings
        .by_attachment
        .get(request.attachment)
        .filter(|binding| binding.identity == *request.identity)
        .filter(|binding| binding.capability.covers(request.target))
        .filter(|binding| binding.verifier.matches(request.proof))
        .ok_or(CollaborationRefusal::BindingMissing)?;
    if !binding.is_active() {
        return Err(CollaborationRefusal::BindingRevoked);
    }
    if !binding.grants(request.required) {
        return Err(CollaborationRefusal::ScopeMissing);
    }
    Ok(AdmittedCollaborator {
        binding: binding.id.clone(),
        revision: binding.revision,
        attachment: binding.attachment.clone(),
        identity: binding.identity.clone(),
        capability: binding.capability.clone(),
        scope: request.required,
    })
}

/// Recheck an earlier admission against the bindings current at commit.
///
/// # Errors
/// Returns [`CollaborationRefusal::BindingMissing`] when the binding is gone or
/// changed identity, and [`CollaborationRefusal::BindingRevoked`] when it was
/// revoked or its revision moved.
pub fn recheck(
    bindings: &BindingSet,
    admitted: &AdmittedCollaborator,
) -> Result<(), CollaborationRefusal> {
    let binding = bindings
        .by_attachment
        .get(&admitted.attachment)
        .filter(|binding| binding.id == admitted.binding)
        .filter(|binding| binding.identity == admitted.identity)
        .filter(|binding| binding.capability == admitted.capability)
        .ok_or(CollaborationRefusal::BindingMissing)?;
    if !binding.is_active() || binding.revision != admitted.revision {
        return Err(CollaborationRefusal::BindingRevoked);
    }
    if !binding.grants(admitted.scope) {
        return Err(CollaborationRefusal::ScopeMissing);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn t(secs: i64) -> DateTime<Utc> {
        Utc.timestamp_opt(1_800_000_000 + secs, 0).single().unwrap()
    }

    fn identity(subject: &str) -> AdmittedIdentity {
        AdmittedIdentity::new("https://idp", subject, "cosmon-rpp-demo", "demo").unwrap()
    }

    fn owner() -> MoleculeId {
        MoleculeId::new("task-20261002-aaaa").unwrap()
    }

    fn seat(name: &str) -> AdvisorySeatId {
        AdvisorySeatId::new(name).unwrap()
    }

    fn proof(byte: u8) -> AttachmentProof {
        AttachmentProof::from_secret_bytes([byte; PROOF_SECRET_BYTES])
    }

    fn work_binding(
        n: u8,
        subject: &str,
        seat_name: &str,
        scopes: &[CollaborationScope],
    ) -> CollaborationBinding {
        CollaborationBinding::provision(
            BindingSpec {
                identity: identity(subject),
                capability: CollaborationCapability::WorkSeat {
                    owner: owner(),
                    seat: seat(seat_name),
                },
                scopes: scopes.iter().copied().collect(),
                label: None,
            },
            BindingId::from_random([n; 8]),
            AttachmentId::from_random([n; 8]),
            &proof(n),
            t(0),
        )
        .unwrap()
    }

    fn work_target() -> CollaborationTarget {
        CollaborationTarget::Work { owner: owner() }
    }

    /// Two operators share a tenant: pilot A holds seat `implementer`, pilot B holds
    /// seat `reviewer`. Pilot A has a second attachment on another machine.
    fn fleet() -> BindingSet {
        BindingSet::new([
            work_binding(
                1,
                "pilot-a",
                "implementer",
                &[CollaborationScope::WorkWrite],
            ),
            work_binding(2, "pilot-b", "reviewer", &[CollaborationScope::WorkWrite]),
            work_binding(3, "pilot-a", "implementer", &[CollaborationScope::WorkRead]),
        ])
        .unwrap()
    }

    fn try_admit(
        set: &BindingSet,
        subject: &str,
        attachment: u8,
        proof_byte: u8,
        required: CollaborationScope,
    ) -> Result<AdmittedCollaborator, CollaborationRefusal> {
        admit(
            set,
            &AdmissionRequest {
                identity: &identity(subject),
                attachment: &AttachmentId::from_random([attachment; 8]),
                proof: &proof(proof_byte),
                target: &work_target(),
                required,
            },
        )
    }

    #[test]
    fn exact_binding_admits_and_the_binding_chooses_the_seat() {
        let admitted = try_admit(&fleet(), "pilot-a", 1, 1, CollaborationScope::WorkWrite).unwrap();
        let caller = admitted.work_caller().unwrap();
        assert_eq!(caller.seat(), &seat("implementer"));
        assert_eq!(caller.scope_owner(), &owner());
        assert_eq!(caller.sender_evidence(), SenderEvidence::AdmittedNonLocal);
    }

    #[test]
    fn same_tenant_caller_cannot_claim_another_users_seat() {
        // Pilot A presents pilot B's attachment, with its own token and with
        // pilot B's proof alike: the identity check refuses both.
        for proof_byte in [1, 2] {
            assert_eq!(
                try_admit(
                    &fleet(),
                    "pilot-a",
                    2,
                    proof_byte,
                    CollaborationScope::WorkRead
                ),
                Err(CollaborationRefusal::BindingMissing)
            );
        }
    }

    #[test]
    fn same_user_cannot_use_a_second_attachment_without_its_proof() {
        // Attachment 3 belongs to pilot A too, but it presents attachment 1's
        // proof for it.
        assert_eq!(
            try_admit(&fleet(), "pilot-a", 3, 1, CollaborationScope::WorkRead),
            Err(CollaborationRefusal::BindingMissing)
        );
        assert!(try_admit(&fleet(), "pilot-a", 3, 3, CollaborationScope::WorkRead).is_ok());
    }

    #[test]
    fn missing_binding_wrong_target_and_missing_scope_refuse() {
        let set = fleet();
        assert_eq!(
            try_admit(&set, "pilot-c", 9, 9, CollaborationScope::WorkRead),
            Err(CollaborationRefusal::BindingMissing)
        );
        let other = CollaborationTarget::Work {
            owner: MoleculeId::new("task-20261002-bbbb").unwrap(),
        };
        let refused = admit(
            &set,
            &AdmissionRequest {
                identity: &identity("pilot-a"),
                attachment: &AttachmentId::from_random([1; 8]),
                proof: &proof(1),
                target: &other,
                required: CollaborationScope::WorkRead,
            },
        );
        assert_eq!(refused, Err(CollaborationRefusal::BindingMissing));
        assert_eq!(
            try_admit(&set, "pilot-a", 3, 3, CollaborationScope::WorkWrite),
            Err(CollaborationRefusal::ScopeMissing)
        );
    }

    #[test]
    fn revoked_binding_refuses_and_stale_admission_fails_recheck() {
        let set = fleet();
        let admitted = try_admit(&set, "pilot-b", 2, 2, CollaborationScope::WorkWrite).unwrap();
        assert_eq!(recheck(&set, &admitted), Ok(()));

        let revoked_set = BindingSet::new(set.iter().map(|binding| {
            if binding.attachment == AttachmentId::from_random([2; 8]) {
                binding.revoked(t(5))
            } else {
                binding.clone()
            }
        }))
        .unwrap();
        assert_eq!(
            try_admit(&revoked_set, "pilot-b", 2, 2, CollaborationScope::WorkWrite),
            Err(CollaborationRefusal::BindingRevoked)
        );
        assert_eq!(
            recheck(&revoked_set, &admitted),
            Err(CollaborationRefusal::BindingRevoked)
        );
        let gone = BindingSet::new(
            set.iter()
                .filter(|b| b.attachment != AttachmentId::from_random([2; 8]))
                .cloned(),
        )
        .unwrap();
        assert_eq!(
            recheck(&gone, &admitted),
            Err(CollaborationRefusal::BindingMissing)
        );
    }

    #[test]
    fn provisioning_refuses_scopes_outside_the_capability() {
        let error = CollaborationBinding::provision(
            BindingSpec {
                identity: identity("pilot-a"),
                capability: CollaborationCapability::PilotMission { mission: owner() },
                scopes: [CollaborationScope::WorkWrite].into_iter().collect(),
                label: None,
            },
            BindingId::from_random([1; 8]),
            AttachmentId::from_random([1; 8]),
            &proof(1),
            t(0),
        )
        .unwrap_err();
        assert!(matches!(
            error,
            BindingSpecError::ScopeOutsideCapability { .. }
        ));
        assert_eq!(
            CollaborationBinding::provision(
                BindingSpec {
                    identity: identity("pilot-a"),
                    capability: CollaborationCapability::PilotMission { mission: owner() },
                    scopes: BTreeSet::new(),
                    label: None,
                },
                BindingId::from_random([1; 8]),
                AttachmentId::from_random([1; 8]),
                &proof(1),
                t(0),
            ),
            Err(BindingSpecError::NoScope)
        );
    }

    #[test]
    fn duplicate_attachments_make_the_set_untrusted() {
        let first = work_binding(1, "pilot-a", "implementer", &[CollaborationScope::WorkRead]);
        let mut second = work_binding(2, "pilot-b", "reviewer", &[CollaborationScope::WorkRead]);
        second.attachment = first.attachment.clone();
        assert!(matches!(
            BindingSet::new([first, second]),
            Err(BindingSetError::Duplicate { .. })
        ));
    }

    #[test]
    fn proof_never_appears_in_debug_or_in_the_record() {
        let secret = proof(7);
        assert_eq!(format!("{secret:?}"), "AttachmentProof(***)");
        let record = work_binding(7, "pilot-a", "implementer", &[CollaborationScope::WorkRead]);
        let json = serde_json::to_string(&record).unwrap();
        assert!(!json.contains(secret.expose_secret()));
        let parsed = AttachmentProof::parse(secret.expose_secret()).unwrap();
        assert!(record.verifier.matches(&parsed));
        assert!(AttachmentProof::parse("cap1-00").is_err());
    }

    #[test]
    fn records_refuse_unknown_fields() {
        let record = work_binding(4, "pilot-a", "implementer", &[CollaborationScope::WorkRead]);
        let mut value = serde_json::to_value(&record).unwrap();
        value["is_operator"] = serde_json::Value::Bool(true);
        assert!(serde_json::from_value::<CollaborationBinding>(value).is_err());
    }

    #[test]
    fn write_scopes_imply_their_read_scopes_only() {
        assert!(CollaborationScope::WorkWrite.satisfies(CollaborationScope::WorkRead));
        assert!(!CollaborationScope::WorkRead.satisfies(CollaborationScope::WorkWrite));
        assert!(!CollaborationScope::WorkWrite.satisfies(CollaborationScope::SessionsRead));
        assert!(CollaborationScope::SessionsWrite.satisfies(CollaborationScope::SessionsRead));
    }
}
