// SPDX-License-Identifier: Apache-2.0

//! `cosmon-thin-cli` build script — folds the §8p surface canon
//! (`crates/cosmon-rpp-adapter/data/surface_events.txt`) into the
//! compile-time scope table rendered by `cs-thin help`.
//!
//! This replaces the hand-mapped `help::scope_for()` — the doc-comment
//! there admitted it was a copy (« Hand-mapped to mirror the
//! rpp-adapter's `requires` ») and nobody re-synchronised it. The scope
//! now comes from the same canon line that mounts the route.
//!
//! Workspace-relative read: the canon lives in the adapter crate's
//! `data/` dir. This is a workspace-internal coupling (the crate is not
//! published standalone); the shared parser is `cosmon-surface-canon`,
//! the same one `cosmon-rpp-adapter/build.rs` uses — one parser, one
//! source, two folds.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use cosmon_surface_canon::{normalise_path, parse_canon, CanonEvent};

const DATA_FILE: &str = "../cosmon-rpp-adapter/data/surface_events.txt";
const GENERATED_FILE: &str = "surface_scopes_generated.rs";

fn main() {
    println!("cargo:rerun-if-changed={DATA_FILE}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let data_path = manifest_dir.join(DATA_FILE);
    let raw = fs::read_to_string(&data_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", data_path.display()));

    let events = parse_canon(&raw, DATA_FILE).unwrap_or_else(|err| panic!("{err}"));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join(GENERATED_FILE);
    fs::write(&out_path, render(&events))
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn render(events: &[CanonEvent]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by crates/cosmon-thin-cli/build.rs from \
         crates/cosmon-rpp-adapter/data/surface_events.txt.\n",
    );
    out.push_str("// DO NOT EDIT — append to the data file instead.\n\n");

    out.push_str("/// `(METHOD, path, scope)` per canon route. Paths are normalised to\n");
    out.push_str("/// the colon-placeholder form (`:id`) so they compare equal to the\n");
    out.push_str("/// `#[verb]` registry's `VerbDescriptor::path` by plain `==`.\n");
    out.push_str("pub const SURFACE_SCOPES: &[(&str, &str, &str)] = &[\n");
    for ev in events {
        let (method, path) = ev
            .method_path
            .split_once(' ')
            .expect("parse_canon guarantees `METHOD PATH` shape");
        writeln!(
            out,
            "    ({method:?}, {:?}, {:?}),",
            normalise_path(path),
            ev.scope,
        )
        .unwrap();
    }
    out.push_str("];\n");
    out
}
