// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalaxyRef } from "./GalaxyRef";

/**
 * Additive provenance recorded on a [`crate::nucleon_map::Resolved`]
 * when (and only when) the binding was admitted via a verified
 * federation badge rather than a local pin.
 *
 * This is the *entire* structural footprint of the federated case in
 * the admission core (ADR-0023 §MVP garde-fou): an `Option<…>` field,
 * `None` for every local binding. There is deliberately **no**
 * `enum LocalOrFederated` and **no** `bool external` — the federated
 * path must not become an `if` that contaminates admission.
 */
export type FederatedProvenance = { 
/**
 * The badge issuer (`iss`) whose signature was verified.
 */
badge_iss: string, 
/**
 * The galaxy the badge authenticated.
 */
galaxy: GalaxyRef, };
