// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to the galaxy a badge is scoped to.
 *
 * `name` is the human handle (`"speck"`) — convenient, *not* the
 * authority. `digest` is the **`galaxy-seed`**: `BLAKE3` of the
 * canonical `GenesisEvent` (smithy G2, `cosmon_hash::galaxy_seed`).
 * The digest is the self-certifying referent — the verifier can
 * recompute it from the received bundle and it survives the death of
 * the issuer and is independent of either instance's namespace
 * (ADR-0023 §D4). A badge proves *"I have a right to THIS"* by object
 * identity; it never enumerates a namespace prefix (no wildcard ⇒
 * fine granularity forced by the form, capability not ACL).
 */
export type GalaxyRef = { 
/**
 * Human-facing galaxy handle. Display/routing only.
 */
name: string, 
/**
 * The `galaxy-seed` (BLAKE3 of the canonical genesis). Serialized
 * as lowercase hex in JSON, as a 32-byte CBOR byte string in the
 * canonical signed form.
 */
digest: string, };
