// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalaxyRef } from "./GalaxyRef";
import type { SigAlg } from "./SigAlg";

/**
 * A detached, signed federation badge (ADR-0023 MVP-B).
 *
 * Field order here is also the **canonical signed order**; the signed
 * payload is the positional CBOR array of every field *except* `sig`.
 * JSON serialization (used for the Rust→TS contract and for human
 * inspection) renders `digest` and `sig` as hex strings and `alg` as
 * a kebab string; the authoritative interchange form for
 * offline/sneakernet transit is [`ScopeBadge::to_cbor`].
 */
export type ScopeBadge = { 
/**
 * Schema version (see [`SCOPE_BADGE_VERSION`]).
 */
v: number, 
/**
 * Declared signature algorithm.
 */
alg: SigAlg, 
/**
 * Issuer identity — the federated instance that minted the badge
 * (ADR-0023: the foreign `iss`). Authenticated, never trusted to
 * self-authorize.
 */
iss: string, 
/**
 * Subject — the machine/identity key handle the badge speaks for.
 */
sub: string, 
/**
 * The galaxy this badge is scoped to (one object, never a prefix).
 */
galaxy: GalaxyRef, 
/**
 * Expiry, Unix seconds (UTC). Passive revocation (ADR-0023 §D5):
 * badges are short-lived and renewed by re-signing; a stale badge
 * simply stops verifying.
 */
not_after: bigint, 
/**
 * Detached signature over `SCOPE_BADGE_DOMAIN_V1 ++
 * canonical-CBOR(signed fields)`. Hex in JSON, raw CBOR byte
 * string on the wire.
 */
sig: string, };
