// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signature algorithm declared by a [`ScopeBadge`].
 *
 * This is a closed, versioned enum of the algorithms a badge schema
 * *may declare* — distinct from `cosmon-notary`'s open `Scheme`
 * trait. It exists so the wire form carries a single compact tag and
 * the verifier dispatches without parsing a free-form string. New
 * algorithms are added here as new variants (each with a fixed CBOR
 * integer tag); old tags are never reused.
 */
export type SigAlg = "ed25519";
