// SPDX-License-Identifier: AGPL-3.0-only

#![allow(clippy::ignore_without_reason)] // proptest! macro generates #[ignore] without reason
//! Proptest conformance gate — `docs/specs/CosmonRun.tla` refuter.
//!
//! Each property below is a translation of one TLA+ safety invariant from
//! `CosmonRun.tla:167–198`. The 13-action alphabet is generated by
//! [`arb_action`] / [`arb_sanctioned_action`] and fed into
//! [`SpecState::step`]; every post-state is checked against its invariant.
//!
//! # Why proptest, not TLC, in CI
//!
//! TLC already validated the spec locally (see `docs/specs/VALIDATION-REPORT.md`).
//! The gap is impl-side: `crates/cosmon-core/src/spec.rs` must continue to
//! match `CosmonRun.tla`. This suite is the mechanical witness of that
//! alignment. TLC ≡ spec-side proof; proptest ≡ impl-side refuter.
//!
//! # Budget
//!
//! * PR gate (`.github/workflows/ci.yml` job `spec-conformance`):
//!   `PROPTEST_CASES=256`, wall-clock budget ≈ 20 s.
//! * Nightly (`spec-conformance-deep`): `PROPTEST_CASES=50000`, 30-min
//!   timeout, shrinkers on, `--ignored` tests only.
//!
//! # Knuth's theorem-style test layout
//!
//! Each test below opens with a prose-commented loop invariant that the
//! property preserves. The body is a straight transliteration of that
//! invariant into a proptest assertion, in the literate-programming style:
//! state the invariant a loop maintains, then show the code that maintains
//! it.

use cosmon_core::spec::{Action, LockValue, SpecState, Status};
use proptest::prelude::*;

// ---------------------------------------------------------------------------
// Strategies — draw from the 13-action alphabet with uniform weight.
// ---------------------------------------------------------------------------

/// Full 13-action alphabet (includes `BypassMerge`).
fn arb_action() -> impl Strategy<Value = Action> {
    prop_oneof![
        Just(Action::Nucleate),
        Just(Action::Tackle),
        Just(Action::Evolve),
        Just(Action::Complete),
        Just(Action::Done),
        Just(Action::Collapse),
        Just(Action::Freeze),
        Just(Action::Thaw),
        Just(Action::LockRelease),
        Just(Action::Purge),
        Just(Action::TmuxCrash),
        Just(Action::ProcessCrash),
        Just(Action::BypassMerge),
    ]
}

/// 12-action alphabet Σ ∖ {`BypassMerge`} — the "closed environment" set over
/// which the positive forms of I6 and I9 are theorems.
fn arb_sanctioned_action() -> impl Strategy<Value = Action> {
    prop_oneof![
        Just(Action::Nucleate),
        Just(Action::Tackle),
        Just(Action::Evolve),
        Just(Action::Complete),
        Just(Action::Done),
        Just(Action::Collapse),
        Just(Action::Freeze),
        Just(Action::Thaw),
        Just(Action::LockRelease),
        Just(Action::Purge),
        Just(Action::TmuxCrash),
        Just(Action::ProcessCrash),
    ]
}

// ---------------------------------------------------------------------------
// I7 — Single event writer (TLA+ lines 187–189)
// ---------------------------------------------------------------------------

// Loop invariant (Knuth §1):
//   lock ∈ {None, Worker} after every step of the trace.
// Preservation: only `Evolve` (→ Worker, guarded by lock = None) and
// `LockRelease` (→ None) mutate the cell. Every other action leaves
// `events_writer_lock` UNCHANGED (TLA+ lines 60–148). Hence |W(t)| ≤ 1
// by structural induction on trace length.
proptest! {
    #[test]
    fn i7_single_event_writer(trace in prop::collection::vec(arb_action(), 0..64)) {
        let mut s = SpecState::init_single();
        prop_assert!(matches!(s.lock(), LockValue::None));
        for a in trace {
            s.step(a);
            prop_assert!(matches!(s.lock(), LockValue::None | LockValue::Worker));
        }
    }
}

// ---------------------------------------------------------------------------
// I9 — Branch merged ⇒ status terminal (TLA+ lines 197–198, Gödel sentence)
// ---------------------------------------------------------------------------

// Loop invariant on Σ = {13 actions} ∖ {BypassMerge} (Knuth §2):
//   branch_merged ⇒ status ∈ {Completed, Collapsed}.
// Preservation: `Done` is the sole in-band mutator of `branch_merged`
// and is guarded by `mol_status = Completed` (TLA+ line 88). No other
// sanctioned action flips the bit. The implication is trivially
// maintained.
proptest! {
    #[test]
    fn i9_merged_implies_terminal(
        trace in prop::collection::vec(arb_sanctioned_action(), 0..64)
    ) {
        let mut s = SpecState::init_single();
        for a in trace {
            s.step(a);
            if s.branch_merged() {
                prop_assert!(
                    s.status().is_terminal(),
                    "I9 violated: branch_merged with status {:?}",
                    s.status()
                );
            }
        }
    }
}

// Gödel witness — I9 is falsified in exactly 2 steps when `BypassMerge`
// enters Next. See `docs/specs/VALIDATION-REPORT.md` §"Model 6".
#[test]
fn i9_falsifies_under_bypass() {
    let mut s = SpecState::init_single();
    s.step(Action::Nucleate);
    s.step(Action::BypassMerge);
    assert!(s.branch_merged(), "BypassMerge must flip branch_merged");
    assert!(
        !s.status().is_terminal(),
        "I9 witness: status is non-terminal ({:?}) yet branch_merged",
        s.status()
    );
}

// ---------------------------------------------------------------------------
// I6 — No ghost fleet entry (TLA+ lines 182–183)
// ---------------------------------------------------------------------------

// Loop invariant on Σ ∖ {BypassMerge} (the in-band + async-crashes
// model, i.e. `CosmonRun_Crashes.cfg`):
//   fleet_desired = Registered ⇒ status ∈ {Running, Frozen}.
// Preservation: `Tackle` sets fleet_desired together with status =
// Running (atomic bundle on TLA+ lines 63–68). `Complete` /
// `Collapse` / `Purge` clear fleet_desired atomically. `Freeze`
// keeps fleet_desired Registered but transitions status Running →
// Frozen, which remains in the RHS set. No other action touches
// fleet_desired.
//
// This is the invariant that Model 3 in `VALIDATION-REPORT.md` shows
// holds only because `Complete` atomically clears fleet_desired. The
// proptest below is the impl-side regression that keeps the `Complete`
// transition atomic.
proptest! {
    #[test]
    fn i6_no_ghost_fleet(trace in prop::collection::vec(arb_sanctioned_action(), 0..64)) {
        use cosmon_core::spec::FleetValue;
        let mut s = SpecState::init_single();
        for a in trace {
            s.step(a);
            if matches!(s.fleet_desired(), FleetValue::Registered) {
                prop_assert!(
                    matches!(s.status(), Status::Running | Status::Frozen),
                    "I6 violated: fleet=Registered with status {:?}",
                    s.status()
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------
// I3 / I4 — Eventual-safety regression fixtures (TLA+ Models 4 and 5)
// ---------------------------------------------------------------------------

// I3 Model 4 (`CosmonRun_CrashesI3.cfg`): `Nucleate → Tackle → TmuxCrash`
// violates stepwise safety of `fleet=Registered ⇒ tmux_session`. After
// `Purge` (the documented liveness witness L2), the invariant is restored.
#[test]
fn i3_fleet_mirrors_eventually() {
    use cosmon_core::spec::FleetValue;

    let mut s = SpecState::init_single();
    s.step(Action::Nucleate);
    s.step(Action::Tackle);
    s.step(Action::TmuxCrash);
    assert!(matches!(s.fleet_desired(), FleetValue::Registered));
    assert!(
        !s.tmux_session(),
        "Model 4 witness: tmux died under Registered"
    );

    // Environment must also crash the worker before Purge is enabled
    // (TLA+ line 119: `~worker_pid_alive[m]`).
    s.step(Action::ProcessCrash);
    assert!(s.enabled(Action::Purge), "Purge must be enabled post-crash");
    s.step(Action::Purge);
    assert!(matches!(s.fleet_desired(), FleetValue::None));
    assert!(
        !s.tmux_session(),
        "I3 restored: fleet cleared and tmux clean"
    );
}

// I4 Model 5 (`CosmonRun_CrashesI4.cfg`):
// `Nucleate → Tackle → Evolve → ProcessCrash` violates stepwise safety of
// `tmux_session ⇒ worker_pid_alive`. The documented resolution is:
// Purge drops the fleet + tmux, after which the invariant holds vacuously.
#[test]
fn i4_session_implies_live() {
    let mut s = SpecState::init_single();
    s.step(Action::Nucleate);
    s.step(Action::Tackle);
    s.step(Action::Evolve);
    s.step(Action::ProcessCrash);
    assert!(s.tmux_session(), "Model 5 witness: tmux still alive");
    assert!(!s.worker_pid_alive(), "Model 5 witness: worker dead");

    s.step(Action::Purge);
    assert!(!s.tmux_session(), "I4 restored vacuously: tmux cleared");
    assert!(!s.worker_pid_alive());
}

// ---------------------------------------------------------------------------
// Deep-suite — nightly `PROPTEST_CASES=50000` runs this.
// The `#[ignore]` flag matches torvalds' CI job spec (§6 of the delib):
//   cargo test ... -- --ignored
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 5_000,
        ..ProptestConfig::default()
    })]

    /// Deep proptest — longer traces, more cases. Ignored by default so the
    /// PR gate stays under 30 s; nightly CI picks it up via `--ignored`.
    #[test]
    #[ignore]
    fn i7_i9_deep_suite(trace in prop::collection::vec(arb_sanctioned_action(), 0..256)) {
        let mut s = SpecState::init_single();
        for a in trace {
            s.step(a);
            prop_assert!(matches!(s.lock(), LockValue::None | LockValue::Worker));
            if s.branch_merged() {
                prop_assert!(s.status().is_terminal());
            }
        }
    }
}
