// SPDX-License-Identifier: AGPL-3.0-only

//! `cosmon-rpp-adapter` build script — folds `data/surface_events.txt`
//! into a compile-time `SurfaceEvent` array, including the enriched
//! per-event columns (exposure, blurb).
//!
//! The §8p frozen API surface used to live as a hand-edited
//! `&'static [&'static str]` inside `src/lib.rs`. Every molecule that
//! mounted a new route had to bump a hard-coded length assertion in
//! two test files, which produced "naïve +1" merge conflicts whenever
//! two task branches landed in parallel (v1.4 drain: 5 such conflicts;
//! v1.5 drain: 6).
//!
//! The data file is append-only. This script parses it once per build
//! (via the shared `cosmon-surface-canon` parser, also used by
//! `cosmon-thin-cli/build.rs`), emits a `SurfaceEvent` const array, and
//! lets the test suite derive its length from `EVENTS.len()` — no
//! integer in source code ever refers to the surface size.
//!
//! Since the column enrichment, each event also carries the route's
//! principal, minimal scope, §8p exposure classification, and blurb —
//! the columns that replaced the hand-maintained `is_adapter_only()` /
//! `forbidden` copies in `tests/api_surface_freeze.rs` and
//! `help::scope_for` in `cosmon-thin-cli`. An ambiguous line refuses
//! to build (the parser returns `Err`, we panic with `file:line`).

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use cosmon_surface_canon::{parse_canon, CanonEvent};

const DATA_FILE: &str = "data/surface_events.txt";
const GENERATED_FILE: &str = "surface_events_generated.rs";

fn main() {
    println!("cargo:rerun-if-changed={DATA_FILE}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let data_path = manifest_dir.join(DATA_FILE);
    let raw = fs::read_to_string(&data_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", data_path.display()));

    let events = parse_canon(&raw, DATA_FILE).unwrap_or_else(|err| panic!("{err}"));
    assert!(
        !events.is_empty(),
        "{DATA_FILE} contains no events — at least the V0 read-only base must be declared",
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join(GENERATED_FILE);
    fs::write(&out_path, render(&events))
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn render(events: &[CanonEvent]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by crates/cosmon-rpp-adapter/build.rs from data/surface_events.txt.\n",
    );
    out.push_str("// DO NOT EDIT — append to the data file instead.\n\n");

    out.push_str("/// Compile-time fold of `data/surface_events.txt`. Each entry is one\n");
    out.push_str("/// `surface_added` event posed by the molecule that mounted the route.\n");
    out.push_str("pub const SURFACE_EVENTS: &[SurfaceEvent] = &[\n");
    for ev in events {
        out.push_str("    SurfaceEvent {\n");
        writeln!(out, "        method_path: {:?},", ev.method_path).unwrap();
        writeln!(out, "        molecule_id: {:?},", ev.molecule_id).unwrap();
        writeln!(out, "        timestamp: {:?},", ev.timestamp).unwrap();
        writeln!(out, "        principal: {:?},", ev.principal).unwrap();
        writeln!(out, "        scope: {:?},", ev.scope).unwrap();
        writeln!(out, "        exposure: {},", ev.exposure.as_variant()).unwrap();
        writeln!(out, "        blurb: {:?},", ev.blurb).unwrap();
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");

    out.push_str("/// Projection of [`SURFACE_EVENTS`] to the bare `\"METHOD PATH\"` strings\n");
    out.push_str("/// returned by [`crate::frozen_api_surface`].\n");
    out.push_str("pub const SURFACE_ROUTES: &[&str] = &[\n");
    for ev in events {
        writeln!(out, "    {:?},", ev.method_path).unwrap();
    }
    out.push_str("];\n");
    out
}
