#!/usr/bin/env bash
# build-cs-musl.sh — cross-compile the `cs` binary to a FULLY-STATIC
# x86_64-unknown-linux-musl on the Mac, and pin its BLAKE3 + toolchain.
# C2 of delib-20260705-7288 ("Sovereign cosmon on LPTHE"), D1 distribution model:
# dev on the Mac, ship a static musl binary (g5's glibc is unknown/unmodifiable
# without root, so we link nothing dynamically).
#
# Cross-linker: cargo-zigbuild (zig cc) — no Docker, no glibc sysroot. The
# workspace's TLS backend is rustls/ring (root Cargo.toml), NOT native-tls, so
# there is no openssl-sys to cross-compile.
#
# The binary is REPRODUCIBLE-WITHOUT-A-CONTAINER (niel Q5): this script records
# the exact rustc/zig versions + a BLAKE3 content hash into MANIFEST.txt. A
# rebuild on the same toolchain yields the same hash; provision.sh re-verifies it
# on g5 before running.
#
# Usage:
#   build-cs-musl.sh [--out DIR]
#     --out DIR   where to place cs + MANIFEST.txt.  Default: <repo>/dist/lpthe
#
# Requires (on the Mac): rustup target add x86_64-unknown-linux-musl,
#   cargo install cargo-zigbuild, brew install zig b3sum.
#
# Exit: 0 built + pinned · 2 usage · 3 missing tool · 4 build failed.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TARGET="x86_64-unknown-linux-musl"
OUT="$REPO/dist/lpthe"

while [ $# -gt 0 ]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    -h|--help) sed -n '1,30p' "$0"; exit 0 ;;
    *) echo "build-cs-musl: unknown arg: $1" >&2; exit 2 ;;
  esac
done

need() { command -v "$1" >/dev/null 2>&1 || { echo "build-cs-musl: missing tool: $1 ($2)" >&2; exit 3; }; }
need cargo "rustup"
need zig   "brew install zig"
command -v cargo-zigbuild >/dev/null 2>&1 || { echo "build-cs-musl: missing cargo-zigbuild (cargo install cargo-zigbuild)" >&2; exit 3; }
rustup target list --installed 2>/dev/null | grep -qx "$TARGET" \
  || { echo "build-cs-musl: target $TARGET not installed (rustup target add $TARGET)" >&2; exit 3; }

echo "==> cross-compiling cs → $TARGET (static musl, rustls)"
( cd "$REPO" && cargo zigbuild --release --target "$TARGET" -p cosmon-cli --bin cs ) \
  || { echo "build-cs-musl: cargo zigbuild failed" >&2; exit 4; }

BIN="$REPO/target/$TARGET/release/cs"
[ -x "$BIN" ] || { echo "build-cs-musl: expected binary not found: $BIN" >&2; exit 4; }

# Static-ness assertion. A static musl binary has NO dynamic interpreter; the
# Mach-O `file` on macOS can't parse ELF interpreter fields, so we grep the ELF
# header bytes: dynamic ELFs carry a PT_INTERP ".interp"/"/lib/ld-*" string.
if strings -n 6 "$BIN" 2>/dev/null | grep -qE '^/lib.*ld-|ld-linux'; then
  echo "build-cs-musl: WARNING — binary appears to reference a dynamic loader (not fully static?)" >&2
else
  echo "    static check: no dynamic loader reference found (good)"
fi

mkdir -p "$OUT"
cp "$BIN" "$OUT/cs"
chmod +x "$OUT/cs"

# ── pin: version + toolchain + BLAKE3 ───────────────────────────────────────
b3() { b3sum "$1" | awk '{print $1}'; }
command -v b3sum >/dev/null 2>&1 || { echo "build-cs-musl: missing b3sum (brew install b3sum)" >&2; exit 3; }

VER="$(cd "$REPO" && awk -F'"' '/^version[[:space:]]*=/{print $2; exit}' Cargo.toml)"
GITHASH="$(cd "$REPO" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
RUSTC_V="$(rustc --version)"
ZIG_V="$(zig version)"
# NB: probe the installed version registry — never `cargo zigbuild` with no
# args, which defaults to a full HOST build (minutes of wasted compile).
ZIGBUILD_V="$(cargo install --list 2>/dev/null | grep -oE 'cargo-zigbuild v[0-9.]+' | grep -oE '[0-9.]+' | head -1 || echo '?')"
CS_B3="$(b3 "$OUT/cs")"
BYTES="$(wc -c < "$OUT/cs" | tr -d ' ')"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$OUT/MANIFEST.txt" <<EOF
# cosmon sovereign build manifest — reproducibility-without-a-container (niel Q5)
# Generated by scripts/lpthe/build-cs-musl.sh. provision.sh re-verifies cs_blake3
# on g5 before running the binary.
name        = cs
version     = $VER
git_commit  = $GITHASH
target      = $TARGET
static      = musl (fully static, no dynamic loader)
tls_backend = rustls (ring) — no openssl/native-tls
size_bytes  = $BYTES
cs_blake3   = $CS_B3
rustc       = $RUSTC_V
zig         = $ZIG_V
zigbuild    = $ZIGBUILD_V
built_at    = $STAMP
built_on    = $(uname -srm)
EOF

echo "==> built cs $VER ($GITHASH) → $OUT/cs"
echo "    BLAKE3 = $CS_B3"
echo "    size   = $BYTES bytes"
echo "    manifest: $OUT/MANIFEST.txt"
